"""add_billing_tables_and_user_balance_fields

Revision ID: 8d5d1ecf1222
Revises: 20260116_links
Create Date: 2026-01-17 00:52:39.573870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5d1ecf1222'
down_revision: Union[str, None] = '20260116_links'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('usd_rub', sa.Float(), nullable=False),
    sa.Column('star_rub', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exchange_rate_date', 'exchange_rates', ['rate_date'], unique=False)
    op.create_index(op.f('ix_exchange_rates_rate_date'), 'exchange_rates', ['rate_date'], unique=True)
    op.create_table('promocodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('min_amount', sa.Float(), nullable=True),
    sa.Column('allowed_services', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=True),
    sa.Column('total_discount_given', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_promocode_active', 'promocodes', ['is_active'], unique=False)
    op.create_index('idx_promocode_code', 'promocodes', ['code'], unique=False)
    op.create_index(op.f('ix_promocodes_code'), 'promocodes', ['code'], unique=True)
    op.create_table('promocode_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_promocode_usage_promo', 'promocode_usages', ['promocode_id'], unique=False)
    op.create_index('idx_promocode_usage_user', 'promocode_usages', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_rub_after', sa.Float(), nullable=False),
    sa.Column('balance_stars_after', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('ad_id', sa.UUID(), nullable=True),
    sa.Column('service_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_created', 'transactions', ['created_at'], unique=False)
    op.create_index('idx_transaction_type', 'transactions', ['type'], unique=False)
    op.create_index('idx_transaction_user', 'transactions', ['user_id'], unique=False)
    op.create_index('idx_transaction_user_created', 'transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('user_service_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_id', sa.UUID(), nullable=True),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_service_active', 'user_service_purchases', ['is_active'], unique=False)
    op.create_index('idx_user_service_ad', 'user_service_purchases', ['ad_id'], unique=False)
    op.create_index('idx_user_service_expires', 'user_service_purchases', ['expires_at'], unique=False)
    op.create_index('idx_user_service_user', 'user_service_purchases', ['user_id'], unique=False)
    op.add_column('payments', sa.Column('payment_type', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('telegram_payment_charge_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('provider_payment_charge_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('promocode_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.alter_column('payments', 'service_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('idx_payment_system', 'payments', ['payment_system'], unique=False)
    op.create_foreign_key(None, 'payments', 'promocodes', ['promocode_id'], ['id'])
    op.add_column('users', sa.Column('balance_rub', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('balance_stars', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_spent_rub', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('total_spent_stars', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('account_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('account_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('extra_ads_limit', sa.Integer(), nullable=True))
    op.create_index('idx_user_account_type', 'users', ['account_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_account_type', table_name='users')
    op.drop_column('users', 'extra_ads_limit')
    op.drop_column('users', 'account_until')
    op.drop_column('users', 'account_type')
    op.drop_column('users', 'total_spent_stars')
    op.drop_column('users', 'total_spent_rub')
    op.drop_column('users', 'balance_stars')
    op.drop_column('users', 'balance_rub')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index('idx_payment_system', table_name='payments')
    op.alter_column('payments', 'service_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('payments', 'discount_amount')
    op.drop_column('payments', 'promocode_id')
    op.drop_column('payments', 'provider_payment_charge_id')
    op.drop_column('payments', 'telegram_payment_charge_id')
    op.drop_column('payments', 'payment_type')
    op.drop_index('idx_user_service_user', table_name='user_service_purchases')
    op.drop_index('idx_user_service_expires', table_name='user_service_purchases')
    op.drop_index('idx_user_service_ad', table_name='user_service_purchases')
    op.drop_index('idx_user_service_active', table_name='user_service_purchases')
    op.drop_table('user_service_purchases')
    op.drop_index('idx_transaction_user_created', table_name='transactions')
    op.drop_index('idx_transaction_user', table_name='transactions')
    op.drop_index('idx_transaction_type', table_name='transactions')
    op.drop_index('idx_transaction_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_promocode_usage_user', table_name='promocode_usages')
    op.drop_index('idx_promocode_usage_promo', table_name='promocode_usages')
    op.drop_table('promocode_usages')
    op.drop_index(op.f('ix_promocodes_code'), table_name='promocodes')
    op.drop_index('idx_promocode_code', table_name='promocodes')
    op.drop_index('idx_promocode_active', table_name='promocodes')
    op.drop_table('promocodes')
    op.drop_index(op.f('ix_exchange_rates_rate_date'), table_name='exchange_rates')
    op.drop_index('idx_exchange_rate_date', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
