"""add_subcategory_condition_delivery

Revision ID: 8da0f021f831
Revises: 4d2a94dc7871
Create Date: 2026-01-06 19:20:38.571838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da0f021f831'
down_revision: Union[str, None] = '4d2a94dc7871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
