"""add_missing_indexes

Revision ID: 9fdb05a48fe3
Revises: 48305ff7214e
Create Date: 2026-01-11 21:58:45.381851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdb05a48fe3'
down_revision: Union[str, None] = '48305ff7214e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ad_expires', 'ads', ['expires_at'], unique=False)
    op.create_index('idx_ad_published', 'ads', ['published_at'], unique=False)
    op.create_index('idx_payment_expires', 'payments', ['expires_at'], unique=False)
    op.create_index('idx_user_banned', 'users', ['is_banned'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_last_activity', 'users', ['last_activity'], unique=False)
    op.create_index('idx_user_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_user_premium', 'users', ['is_premium'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_premium', table_name='users')
    op.drop_index('idx_user_phone', table_name='users')
    op.drop_index('idx_user_last_activity', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_banned', table_name='users')
    op.drop_index('idx_payment_expires', table_name='payments')
    op.drop_index('idx_ad_published', table_name='ads')
    op.drop_index('idx_ad_expires', table_name='ads')
    # ### end Alembic commands ###
