"""add_ad_statuses_deleted_at_and_archived_ads

Revision ID: be9d931bd0d2
Revises: 8d5d1ecf1222
Create Date: 2026-01-20 17:31:35.288262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9d931bd0d2'
down_revision: Union[str, None] = '8d5d1ecf1222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_ads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('ad_type', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('favorites_count', sa.Integer(), nullable=True),
    sa.Column('contacts_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archive_reason', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_archived_ad_date', 'archived_ads', ['archived_at'], unique=False)
    op.create_index('idx_archived_ad_user', 'archived_ads', ['user_id'], unique=False)
    op.create_index(op.f('ix_archived_ads_user_id'), 'archived_ads', ['user_id'], unique=False)
    op.add_column('ads', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'deleted_at')
    op.drop_index(op.f('ix_archived_ads_user_id'), table_name='archived_ads')
    op.drop_index('idx_archived_ad_user', table_name='archived_ads')
    op.drop_index('idx_archived_ad_date', table_name='archived_ads')
    op.drop_table('archived_ads')
    # ### end Alembic commands ###
